use_frameworks!

platform :ios, '8.0'

target 'KWBaseViewController_Example' do
  pod 'KWBaseViewController', :path => '../'

  target 'KWBaseViewController_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
